# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main, staging, and develop branches
  pull_request:
    branches: [ main, staging, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python c
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4

      - name: Install tree
        run: |
          sudo apt-get install -y tree

      - name: Run Pytest
        run: |
          pytest test/*/*.py

      - name: Run Coverage
        run: |
          coverage run -m pytest test/*/*.py

      - name: Run Coverage Report
        run: |
          coverage report

      - name: Show folder structure
        run: |
          tree -L 4

      - name: Verify directory permissions
        run: |
          ls -ld allure/${{ matrix.python-version }}
          ls -l allure/${{ matrix.python-version }}

      - name: Set permissions in Allure report directory
        run: |
          sudo chmod -R u+rwX,go+rwX allure/${{ matrix.python-version }}

      - name: Verify directory permissions again
        run: |
          ls -ld allure/${{ matrix.python-version }}
          ls -l allure/${{ matrix.python-version }}

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          subfolder: allure/${{ matrix.python-version }}
          keep_reports: 7

      - name: Compress Allure report
        run: |
          ZIP_PATH="allure/${{ matrix.python-version }}/allure-report.zip"
          if [ -f "$ZIP_PATH" ]; then
            rm "$ZIP_PATH"
          fi
          zip -r "$ZIP_PATH" allure/${{ matrix.python-version }}/report
          echo "Allure report zipped to $ZIP_PATH"

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.python-version }}
          path: allure/${{ matrix.python-version }}/allure-report.zip

      - name: Deploy test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure
          commit_message: deploy ${{ matrix.python-version }} - ${{ steps.prepare_message.outputs.DEPLOY_COMMIT_MSG }}

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GH_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
