# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main, staging, and develop branches
  pull_request:
    branches: [ main, staging, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python c
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4

      - name: Run Pytest
        run: |
          pytest test/*/*.py

      - name: Run Coverage
        run: |
          coverage run -m pytest test/*/*.py

      - name: Run Coverage Report
        run: |
          coverage report

      - name: Upload test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh_pages
          path: allure/${{ matrix.python-version }}/history

      - name: Generate test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: allure/history
          allure_results: allure/${{ matrix.python-version }}/results
          allure_history: allure/${{ matrix.python-version }}/history
          allure_report: allure/${{ matrix.python-version }}/report

      - name: Instalar tree y mostrar estructura de carpetas
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree -L 2

      - name: Compress Allure report
        run: |
          ZIP_PATH="allure/${{ matrix.python-version }}/allure-report.zip"
          if [ -f "$ZIP_PATH" ]; then
            rm "$ZIP_PATH"
          fi
          zip -r "$ZIP_PATH" allure/report

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.python-version }}
          path: allure/${{ matrix.python-version }}/allure-report.zip

      - name: Deploy test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh_pages
          publish_dir: allure/${{ matrix.python-version }}/report
