name: Linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        update-pip: "false"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run Ruff
      run: ruff check --output-format=github .