name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pylint
# this Action should follow steps to set up Python build environment
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v3
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')